---
- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  vars_prompt:
    - name: pypi_password
      prompt: "pypi password"
      private: yes
      confirm: yes
  roles:
    - homebrew
    - gem
    - npm
    - dotfiles
    - vim
#    - ssh
    - osx