---
# TODO: ssh-keygen
- hosts: localhost
  connection: local
  gather_facts: no
  sudo: no
  vars:
    homebrew_taps:
      - homebrew/binary
      - homebrew/dupes
      - caskroom/cask
      - railwaycat/emacsmacport
      - sanemat/font
    homebrew_packages:
      - { name: mysql }
      - { name: tree }
      - { name: git }
      - { name: pyenv-virtualenv }
      - { name: ansible }
      - { name: erlang }
      - { name: docker }
      - { name: docker-machine }
      - { name: ssh-copy-id }
      - { name: redis }
      - { name: rbenv }
      - { name: coteditor/coteditor/cot }
      - { name: caskroom/cask/brew-cask }
      - { name: the_silver_searcher }
    homebrew_cask_packages:
      - { name: vagrant }
      - { name: virtualbox }
      - { name: google-japanese-ime }
      - { name: coteditor }
      - { name: karaviner }
      - { name: evernote }
      - { name: iterm2 }
      - { name: google-chrome }
      - { name: kibito }
      - { name: sequel-pro }
      - { name: sqlitebrowser }
      - { name: pg-commander }
    npm_global_packages:
      - { name: grunt-cli }
  
  tasks:
    # TODO: 冪等性
    # - name: Agree license
    #   shell: xcodebuild -license

    # - name: Install Xcode tool
    #   shell: xcode-select --install

    # Homebrew

    # TODO: 冪等性
    # - name: Install homebrew
    #   command: ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

    - name: Add homebrew tap repositories
      homebrew_tap: tap={{ item }} state=present
      with_items: homebrew_taps

    - name: Update homebrew
      homebrew: update_homebrew=yes

    - name: Install homebrew packages
      homebrew: >
        name={{ item.name }}
        state={{ item.state | default('latest') }}
        install_options={{
          item.install_options | default() | join(',')
          if item.install_options is not string
          else item.install_options
        }}
      with_items: homebrew_packages
      register: brew_result

    # Homebrew cask

    #- name: Install Homebrew cask packages
    #  homebrew_cask: name={{ item.name }} state={{ item.state|default('installed') }}
    #  with_items: homebrew_cask_packages
    #  register: cask_result

    # NPM
    # TODO: npm自体のインストール

    - name: Install global npm packages
      npm: name={{ item.name }} state={{ item.state|default('latest') }} global=yes
      with_items: npm_global_packages
      register: npm_result

    # vim

    - name: Create a directory of Neobundle
      file: path=~/.vim/bundle state=directory

    - name: Install Neobundle
      git: repo=git://github.com/Shougo/neobundle.vim dest=~/.vim/bundle/neobundle.vim accept_hostkey=no

    # dotfiles

    - name: Create adirectory of Dotfiles
      file: path=~/Projects state=directory

    - name: Clone dotfiles
      git: repo=git@github.com:itkr/dotfiles.git dest=~/Projects/dotfiles

    - name: Copy dotfiles
      copy: src=~/Projects/dotfiles/{{ item }} dest=~/{{ item }}
      with_items:
#        - '.bashrc'
        - '.bash_profile'
        - '.gitconfig'
        - '.vimrc'

    - name: Import Karabiner settings
      script: ~/Projects/dotfiles/karabiner/karabiner-import.sh

