---
- hosts: localhost
  connection: local
  gather_facts: no           
  sudo: no
  vars:
    homebrew_taps:
      - homebrew/binary
      - homebrew/dupes
      - caskroom/cask
      - railwaycat/emacsmacport
      - sanemat/font
    homebrew_packages:
      # - { name: openssl, state: linked, install_options: force }
      # - { name: mysql }
      - { name: tree }
      - { name: git }
      - { name: pyenv-virtualenv }
      - { name: ansible }
#      - { name: erlang }
      - { name: docker }
      - { name: docker-machine }
#      - { name: redis }
#      - { name: rbenv }
#      - { name: coteditor/coteditor/cot }
      - { name: caskroom/cask/brew-cask }
      - { name: the_silver_searcher }
    homebrew_cask_packages:
      # - { name: vagrant }
      # - { name: virtualbox }
      # - { name: emacs-mac }
      - { name: google-japanese-ime }
      # - { name: coteditor }
    npm_global_packages:
      - { name: grunt-cli }
      # - { name: react-tools }
  
  tasks:
    - name: Add homebrew tap repositories
      homebrew_tap: tap={{ item }} state=present
      with_items: homebrew_taps

    - name: Update homebrew
      homebrew: update_homebrew=yes

    # Homebrew

    - name: Install homebrew packages
      homebrew: >
        name={{ item.name }}
        state={{ item.state | default('latest') }}
        install_options={{
          item.install_options | default() | join(',')
          if item.install_options is not string
          else item.install_options
        }}
      with_items: homebrew_packages
      register: brew_result

    # Homebrew cask

    - name: Install Homebrew cask packages
      homebrew_cask: name={{ item.name }} state={{ item.state|default('installed') }}
      with_items: homebrew_cask_packages
      register: cask_result

    # NPM

    - name: Install global npm packages
      npm: name={{ item.name }} state={{ item.state|default('latest') }} global=yes
      with_items: npm_global_packages
      register: npm_result

    # vim

    - name: Create a directory of Neobundle
      file: path=~/.vim/bundle state=directory

    - name: Install Neobundle
      git: repo=git://github.com/Shougo/neobundle.vim dest=~/.vim/bundle/neobundle.vim accept_hostkey=no
