---
- name: Create adirectory of Dotfiles
  file: path=~/.ghq/github.com/itkr state=directory
  ignore_errors: True  # シンボリックリンクにしている場合エラーになるので

# TODO: リポジトリ一緒にしても良いかも
- name: Pull dotfiles
  git: repo=https://github.com/itkr/dotfiles.git dest=~/.ghq/github.com/itkr/dotfiles version=master
  register: pull_dotfiles_result

# TODO: シンボリックリンクにする？
- name: Copy dotfiles
  copy: src=~/.ghq/github.com/itkr/dotfiles/{{ item }} dest=~/{{ item }} force=no
  with_items:
    - '.bash_profile'
    - '.bashrc'
    - '.gitconfig'
    - '.gitignore'
    - '.ideavimrc'
    - '.tmux.conf'
    - '.vimrc'
    - '.vrapperrc'
    - '.zshrc'
    - '.bash/'
    - '.iterm2/'
  when: pull_dotfiles_result | changed

- name: Import Karabiner settings
  script: ~/.ghq/github.com/itkr/dotfiles/karabiner/karabiner-import.sh
  when: pull_dotfiles_result | changed

- name: Copy Karabiner private.xml
  copy: src=~/.ghq/github.com/itkr/dotfiles/karabiner/private.xml dest='~/Library/Application Support/Karabiner/private.xml' force=yes
  when: pull_dotfiles_result | changed

- name: Create pypi settings
  template: >
    src=etc/.pypirc.j2
    dest=~/.pypirc
