---
- name: Create adirectory of Dotfiles
  file: path=/var/tmp state=directory
  ignore_errors: True  # シンボリックリンクにしている場合エラーになるので

- name: Pull dotfiles
  git: repo=git@github.com:itkr/dotfiles.git dest=/var/tmp/dotfiles version=master
  register: pull_dotfiles_result

- name: Copy dotfiles
  copy: src=/var/tmp/dotfiles/{{ item }} dest=~/{{ item }} force=no
  with_items:
    - '.bashrc'
    - '.bash_profile'
    - '.gitconfig'
    - '.gitignore'
    - '.vimrc'
    - '.bash/'
  when: pull_dotfiles_result | changed

- name: Import Karabiner settings
  script: /var/tmp/dotfiles/karabiner/karabiner-import.sh
  when: pull_dotfiles_result | changed

- name: Copy Karabiner private.xml
  copy: src=/var/tmp/dotfiles/karabiner/private.xml dest='~/Library/Application Support/Karabiner/private.xml' force=yes
  when: pull_dotfiles_result | changed
