---
osx_settings:
  # Global
  # フルキーボードアクセスを有効
  - {
      domain: NSGlobalDomain,
      key: AppleKeyboardUIMode,
      type: int,
      value: 3
    }
  # Fuキーを標準のファンクションキーとして使用しない
  - {
      domain: NSGlobalDomain,
      key: com.apple.keyboard.fnState,
      type: bool,
      value: false
    }
  # 拡張子を常に表示
  - {
      domain: NSGlobalDomain,
      key: AppleShowAllExtensions,
      type: bool,
      value: true
    }
  # Dock
  # サイズ
  - {
      domain: com.apple.dock,
      key: tilesize,
      type: float,
      value: 50
    }
  # 拡大を無効にする
  - {
      domain: com.apple.dock,
      key: magnification,
      type: bool,
      value: false
    }
  # Dockを自動的に隠さない
  - {
      domain: com.apple.dock,
      key: autohide,
      type: bool,
      value: false
    }
  # Finder
  # デフォルトはカラムビュー表示
  - {
      domain: com.apple.finder,
      key: FXPreferredViewStyle,
      type: string,
      value: clmv
    }
  # 隠しファイルや隠しフォルダを表示
  - {
      domain: com.apple.finder,
      key: AppleShowAllFiles,
      type: bool,
      value: true
    }
  # Finderの効果音を無効にする
  - {
      domain: com.apple.finder,
      key: FinderSounds,
      type: bool,
      value: false
    }
  # Trackpad
  # タップでクリック   defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -int 1
  - {
      domain: com.apple.driver.AppleBluetoothMultitouch.trackpad,
      key: Clicking,
      type: int,
      value: 1
    }
  # スクロール方向をナチュラルにしない
  - {
      domain: NSGlobalDomain,
      key: com.apple.swipescrolldirection,
      type: bool,
      value: false
    }
  # スクロール方向をナチュラルにしない
  - {
      domain: NSGlobalDomain,
      key: com.apple.swipescrolldirection,
      type: bool,
      value: false
    }

# capslock を controllに
# keyboardid=$(ioreg -n IOHIDKeyboard -r | grep -E 'VendorID"|ProductID' | awk '{ print $4 }' | paste -s -d'-\n' -)'-0'
# defaults -currentHost write -g com.apple.keyboard.modifiermapping.${keyboardid} -array '<dict><key>HIDKeyboardModifierMappingDst</key></dict><integer>2</integer> <key>HIDKeyboardModifierMappingSrc</key><key>0</key>'